apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-server
  template:
    metadata:
      labels:
        app: python-server
    spec:
      containers:
      - name: python-server
        image: mrace17/python-server :1.0.2
        ports:
        - containerPort: 5000


---


apiVersion: v1
kind: Service
metadata:
  name: python-server
spec:
  selector:
    app: python-server
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer

